name: pankbase_degs
channels:
  - defaults
  - conda-forge
  - bioconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.0=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - anndata=0.6.22.post1=py_0
  - anyio=4.6.2=py312h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312h06a4308_0
  - attrs=24.3.0=py312h06a4308_0
  - babel=2.16.0=py312h06a4308_0
  - beautifulsoup4=4.12.3=py312h06a4308_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_1
  - blas=1.0=openblas
  - bleach=6.2.0=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.2=h3394656_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=1.17.1=py312h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py312h06a4308_0
  - curl=8.11.1=h332b0f4_0
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h7b6447c_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_1
  - gfortran_impl_linux-64=11.2.0=h7a446d4_16
  - gfortran_linux-64=11.2.0=hc2dff05_1
  - glib=2.82.2=h07242d1_1
  - glib-tools=2.82.2=h4833e2c_1
  - graphite2=1.3.14=h295c915_1
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_1
  - h11=0.14.0=py312h06a4308_0
  - h5py=3.13.0=nompi_py312hedeef09_100
  - harfbuzz=9.0.0=hda332d3_1
  - hdf5=1.14.3=nompi_h2d575fe_109
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.27.0=py312h06a4308_0
  - icu=75.1=he02047a_0
  - idna=3.7=py312h06a4308_0
  - ipykernel=6.29.5=py312h06a4308_1
  - ipython=8.30.0=py312h06a4308_0
  - jedi=0.19.2=py312h06a4308_0
  - jinja2=3.1.5=py312h06a4308_0
  - json5=0.9.25=py312h06a4308_0
  - jsonschema=4.23.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter-lsp=2.2.0=py312h06a4308_0
  - jupyter_client=8.6.3=py312h06a4308_0
  - jupyter_core=5.7.2=py312h06a4308_0
  - jupyter_events=0.10.0=py312h06a4308_0
  - jupyter_server=2.14.1=py312h06a4308_0
  - jupyter_server_terminals=0.4.4=py312h06a4308_1
  - jupyterlab=4.3.4=py312h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=8.11.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgit2=1.8.4=hd24f944_1
  - libglib=2.82.2=h2ff4ddf_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=16_linux64_openblas
  - liblzma=5.6.3=hb9d3cd8_1
  - liblzma-devel=5.6.3=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.46=h943b412_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=h8d12d68_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.9.4=h6a678d5_1
  - make=4.2.1=h1bed415_1
  - markupsafe=2.1.3=py312h5eee18b_1
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mistune=2.0.4=py312h06a4308_0
  - natsort=8.4.0=pyh29332c3_1
  - nb_conda_kernels=2.5.2=py312h06a4308_0
  - nbclient=0.8.0=py312h06a4308_0
  - nbconvert=7.16.4=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - nlopt=2.8.0=py312h69683c5_2
  - notebook-shim=0.2.3=py312h06a4308_0
  - numpy=2.0.1=py312h2809609_1
  - numpy-base=2.0.1=py312he1a6c75_1
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.4.0=py312h06a4308_0
  - packaging=24.2=py312h06a4308_0
  - pandas=2.3.3=py312hf79963d_1
  - pandoc=3.6.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.54.0=h3a902e7_3
  - parso=0.8.4=py312h06a4308_0
  - pcre=8.45=h295c915_0
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=25.0=py312h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=3.10.0=py312h06a4308_0
  - prometheus_client=0.21.0=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h5eee18b_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312h06a4308_1
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-json-logger=3.2.1=py312h06a4308_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=26.2.0=py312h6a678d5_0
  - r-abind=1.4_5=r44hc72bb7e_1006
  - r-askpass=1.2.1=r44h2b5f3a1_0
  - r-assertthat=0.2.1=r44hc72bb7e_5
  - r-backports=1.5.0=r44hb1dbf0f_1
  - r-base=4.4.2=hc737e89_2
  - r-base64enc=0.1_3=r44hb1dbf0f_1007
  - r-boot=1.3_31=r44hc72bb7e_0
  - r-brew=1.0_10=r44hc72bb7e_1
  - r-brio=1.1.5=r44hb1dbf0f_1
  - r-broom=1.0.7=r44hc72bb7e_0
  - r-bslib=0.8.0=r44hc72bb7e_0
  - r-cachem=1.1.0=r44hb1dbf0f_1
  - r-callr=3.7.6=r44hc72bb7e_1
  - r-car=3.1_3=r44hc72bb7e_0
  - r-cardata=3.0_5=r44hc72bb7e_3
  - r-caret=6.0_94=r44hdb488b9_2
  - r-catboost=1.2.8=r44ha770c72_0
  - r-checkmate=2.3.2=r44hdb488b9_0
  - r-class=7.3_23=r44h2b5f3a1_0
  - r-cli=3.6.3=r44h0d4f4ea_1
  - r-clipr=0.8.0=r44hc72bb7e_3
  - r-clock=0.7.1=r44h0d4f4ea_0
  - r-cluster=2.1.8=r44hb67ce94_0
  - r-codetools=0.2_20=r44hc72bb7e_1
  - r-colorspace=2.1_1=r44hdb488b9_0
  - r-commonmark=1.9.2=r44h2b5f3a1_0
  - r-conquer=1.3.3=r44hb424bfc_4
  - r-corrplot=0.95=r44hc72bb7e_0
  - r-cowplot=1.1.3=r44hc72bb7e_1
  - r-cpp11=0.5.1=r44hc72bb7e_0
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-credentials=2.0.2=r44hc72bb7e_0
  - r-crosstalk=1.2.1=r44hc72bb7e_1
  - r-curl=6.0.1=r44h2700575_0
  - r-data.table=1.16.4=r44he23165d_0
  - r-deldir=2.0_4=r44hbcb9c34_1
  - r-deriv=4.1.6=r44hc72bb7e_0
  - r-desc=1.4.3=r44hc72bb7e_1
  - r-devtools=2.4.5=r44hc72bb7e_3
  - r-diagram=1.6.5=r44ha770c72_3
  - r-diffobj=0.3.5=r44hb1dbf0f_3
  - r-digest=0.6.37=r44h0d4f4ea_0
  - r-doby=4.6.25=r44hc72bb7e_0
  - r-downlit=0.4.4=r44hc72bb7e_1
  - r-dplyr=1.1.4=r44h0d4f4ea_1
  - r-e1071=1.7_16=r44h93ab643_0
  - r-ellipsis=0.3.2=r44hb1dbf0f_3
  - r-evaluate=1.0.3=r44hc72bb7e_0
  - r-fansi=1.0.6=r44hb1dbf0f_1
  - r-farver=2.1.2=r44ha18555a_1
  - r-fastmap=1.2.0=r44ha18555a_1
  - r-fontawesome=0.5.3=r44hc72bb7e_0
  - r-foreach=1.5.2=r44hc72bb7e_3
  - r-foreign=0.8_88=r44h2b5f3a1_0
  - r-formula=1.2_5=r44hc72bb7e_2
  - r-fs=1.6.5=r44h93ab643_0
  - r-future=1.34.0=r44h785f33e_0
  - r-future.apply=1.11.3=r44hc72bb7e_0
  - r-generics=0.1.3=r44hc72bb7e_3
  - r-gert=2.1.4=r44h017ce79_0
  - r-ggcorrplot=0.1.4.1=r44hc72bb7e_1
  - r-ggplot2=3.5.1=r44hc72bb7e_1
  - r-ggpubr=0.6.0=r44hc72bb7e_2
  - r-ggrepel=0.9.6=r44h93ab643_0
  - r-ggsci=3.2.0=r44hc72bb7e_1
  - r-ggsignif=0.6.4=r44hc72bb7e_2
  - r-gh=1.4.1=r44hc72bb7e_1
  - r-gitcreds=0.1.2=r44hc72bb7e_3
  - r-globals=0.16.3=r44hc72bb7e_1
  - r-glue=1.8.0=r44h2b5f3a1_0
  - r-gower=1.0.1=r44hb1dbf0f_2
  - r-gridextra=2.3=r44hc72bb7e_1006
  - r-gtable=0.3.6=r44hc72bb7e_0
  - r-hardhat=1.4.1=r44hc72bb7e_0
  - r-here=1.0.1=r44hc72bb7e_3
  - r-hexbin=1.28.5=r44hb67ce94_0
  - r-highr=0.11=r44hc72bb7e_1
  - r-hmisc=5.2_2=r44hb67ce94_0
  - r-htmltable=2.4.3=r44hc72bb7e_0
  - r-htmltools=0.5.8.1=r44ha18555a_1
  - r-htmlwidgets=1.6.4=r44h785f33e_3
  - r-httpuv=1.6.15=r44ha18555a_1
  - r-httr=1.4.7=r44hc72bb7e_1
  - r-httr2=1.1.0=r44hc72bb7e_0
  - r-ini=0.3.1=r44hc72bb7e_1006
  - r-interp=1.1_6=r44ha936806_1
  - r-ipred=0.9_15=r44hdb488b9_1
  - r-irdisplay=1.1=r44hd8ed1ab_3
  - r-irkernel=1.3.2=r44h785f33e_2
  - r-isoband=0.2.7=r44ha18555a_3
  - r-iterators=1.0.14=r44hc72bb7e_3
  - r-jpeg=0.1_10=r44had62be2_6
  - r-jquerylib=0.1.4=r44hc72bb7e_3
  - r-jsonlite=1.8.9=r44h2b5f3a1_0
  - r-kernsmooth=2.23_26=r44h8461fee_0
  - r-knitr=1.49=r44hc72bb7e_0
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-later=1.4.1=r44h93ab643_0
  - r-lattice=0.22_6=r44hb1dbf0f_1
  - r-latticeextra=0.6_30=r44hc72bb7e_3
  - r-lava=1.8.1=r44hc72bb7e_0
  - r-lazyeval=0.2.2=r44hb1dbf0f_5
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-listenv=0.9.1=r44hc72bb7e_1
  - r-lme4=1.1_35.5=r44h0d4f4ea_1
  - r-lubridate=1.9.4=r44h2b5f3a1_0
  - r-magrittr=2.0.3=r44hb1dbf0f_3
  - r-mass=7.3_64=r44h2b5f3a1_0
  - r-matrix=1.7_2=r44h2ae2be5_0
  - r-matrixmodels=0.5_3=r44hc72bb7e_1
  - r-matrixstats=1.5.0=r44h2b5f3a1_0
  - r-memoise=2.0.1=r44hc72bb7e_3
  - r-mgcv=1.9_1=r44h0d28552_1
  - r-microbenchmark=1.5.0=r44h2b5f3a1_0
  - r-mime=0.12=r44hb1dbf0f_3
  - r-miniui=0.1.1.1=r44hc72bb7e_1005
  - r-minqa=1.2.8=r44ha936806_0
  - r-modelmetrics=1.2.2.2=r44h0d4f4ea_4
  - r-modelr=0.1.11=r44hc72bb7e_2
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-nlme=3.1_167=r44hb67ce94_0
  - r-nloptr=2.1.1=r44h9b87a3a_1
  - r-nnet=7.3_20=r44h2b5f3a1_0
  - r-numderiv=2016.8_1.1=r44hc72bb7e_6
  - r-openssl=2.2.2=r44he8289e2_0
  - r-parallelly=1.42.0=r44h2b5f3a1_0
  - r-paws=0.9.0=r44hc72bb7e_1
  - r-paws.analytics=0.9.0=r44hc72bb7e_1
  - r-paws.application.integration=0.9.0=r44hc72bb7e_1
  - r-paws.common=0.8.8=r44h3697838_0
  - r-paws.compute=0.9.0=r44hc72bb7e_1
  - r-paws.cost.management=0.9.0=r44hc72bb7e_1
  - r-paws.customer.engagement=0.9.0=r44hc72bb7e_1
  - r-paws.database=0.9.0=r44hc72bb7e_1
  - r-paws.developer.tools=0.9.0=r44hc72bb7e_1
  - r-paws.end.user.computing=0.9.0=r44hc72bb7e_1
  - r-paws.machine.learning=0.9.0=r44hc72bb7e_1
  - r-paws.management=0.9.0=r44hc72bb7e_1
  - r-paws.networking=0.9.0=r44hc72bb7e_1
  - r-paws.security.identity=0.9.0=r44hc72bb7e_1
  - r-paws.storage=0.9.0=r44hc72bb7e_1
  - r-pbdzmq=0.3_13=r44h549f438_0
  - r-pbkrtest=0.5.3=r44hc72bb7e_0
  - r-pillar=1.10.1=r44hc72bb7e_0
  - r-pkgbuild=1.4.6=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-pkgdown=2.1.1=r44hc72bb7e_0
  - r-pkgload=1.4.0=r44hc72bb7e_0
  - r-plotly=4.10.4=r44hc72bb7e_1
  - r-plyr=1.8.9=r44ha18555a_1
  - r-png=0.1_8=r44h21f035c_2
  - r-polynom=1.4_1=r44hc72bb7e_3
  - r-praise=1.0.0=r44hc72bb7e_1008
  - r-prettyunits=1.2.0=r44hc72bb7e_1
  - r-proc=1.18.5=r44ha18555a_1
  - r-processx=3.8.5=r44h2b5f3a1_0
  - r-prodlim=2024.06.25=r44h0d4f4ea_1
  - r-profvis=0.4.0=r44h2b5f3a1_0
  - r-progressr=0.15.1=r44hc72bb7e_0
  - r-promises=1.3.2=r44h93ab643_0
  - r-proxy=0.4_27=r44hb1dbf0f_3
  - r-ps=1.8.1=r44h2b5f3a1_0
  - r-purrr=1.0.2=r44hdb488b9_1
  - r-quantreg=6.00=r44h012206f_0
  - r-r6=2.5.1=r44hc72bb7e_3
  - r-ragg=1.3.3=r44h9aa3752_0
  - r-rappdirs=0.3.3=r44hb1dbf0f_3
  - r-rcmdcheck=1.4.0=r44h785f33e_3
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-rcpp=1.0.14=r44h93ab643_0
  - r-rcpparmadillo=14.2.3_1=r44hc2d650c_0
  - r-rcppeigen=0.3.4.0.2=r44hb79369c_0
  - r-rcpptoml=0.2.2=r44ha18555a_2
  - r-recipes=1.1.0=r44hc72bb7e_1
  - r-rematch2=2.1.2=r44hc72bb7e_4
  - r-remotes=2.5.0=r44hc72bb7e_1
  - r-repr=1.1.7=r44h785f33e_1
  - r-reshape2=1.4.4=r44h0d4f4ea_4
  - r-reticulate=1.40.0=r44h93ab643_0
  - r-rlang=1.1.5=r44h93ab643_0
  - r-rmarkdown=2.29=r44hc72bb7e_0
  - r-roxygen2=7.3.2=r44h0d4f4ea_1
  - r-rpart=4.1.24=r44h2b5f3a1_0
  - r-rprojroot=2.0.4=r44hc72bb7e_1
  - r-rstatix=0.7.2=r44hc72bb7e_2
  - r-rstudioapi=0.17.1=r44hc72bb7e_0
  - r-rversions=2.1.2=r44hc72bb7e_3
  - r-sass=0.4.9=r44ha18555a_1
  - r-scales=1.3.0=r44hc72bb7e_1
  - r-sessioninfo=1.2.2=r44hc72bb7e_3
  - r-shape=1.4.6.1=r44ha770c72_1
  - r-shiny=1.10.0=r44h785f33e_0
  - r-sourcetools=0.1.7_1=r44ha18555a_2
  - r-sparsem=1.84_2=r44hc4980d5_0
  - r-sparsevctrs=0.2.0=r44h2b5f3a1_1
  - r-squarem=2021.1=r44hc72bb7e_3
  - r-stringi=1.8.4=r44h33cde33_3
  - r-stringr=1.5.1=r44h785f33e_1
  - r-survival=3.8_3=r44h2b5f3a1_0
  - r-sys=3.4.3=r44h2b5f3a1_0
  - r-systemfonts=1.2.1=r44h5c043a3_0
  - r-testthat=3.2.1.1=r44h0d4f4ea_1
  - r-textshaping=0.4.0=r44ha47bcaa_2
  - r-tibble=3.2.1=r44hdb488b9_3
  - r-tidyr=1.3.1=r44h0d4f4ea_1
  - r-tidyselect=1.2.1=r44hc72bb7e_1
  - r-timechange=0.3.0=r44ha18555a_1
  - r-timedate=4041.110=r44hc72bb7e_0
  - r-tinytex=0.54=r44hc72bb7e_0
  - r-tzdb=0.4.0=r44ha18555a_2
  - r-urlchecker=1.0.1=r44hc72bb7e_3
  - r-usethis=3.1.0=r44hc72bb7e_0
  - r-utf8=1.2.4=r44hb1dbf0f_1
  - r-uuid=1.2_1=r44hdb488b9_0
  - r-vctrs=0.6.5=r44h0d4f4ea_1
  - r-viridis=0.6.5=r44hc72bb7e_1
  - r-viridislite=0.4.2=r44hc72bb7e_2
  - r-waldo=0.6.1=r44hc72bb7e_0
  - r-whisker=0.4.1=r44hc72bb7e_2
  - r-withr=3.0.2=r44hc72bb7e_0
  - r-xfun=0.50=r44h93ab643_0
  - r-xml2=1.3.6=r44h8194278_2
  - r-xopen=1.0.1=r44hc72bb7e_1
  - r-xtable=1.8_4=r44hc72bb7e_6
  - r-yaml=2.3.10=r44hdb488b9_0
  - r-zip=2.3.1=r44hb1dbf0f_1
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.32.3=py312h06a4308_1
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rpds-py=0.22.3=py312h4aa5aa6_0
  - scipy=1.16.0=py312hf734454_0
  - sed=4.8=he412f7d_0
  - send2trash=1.8.2=py312h06a4308_1
  - setuptools=75.8.0=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - sqlite=3.45.2=h2c6b66d_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - terminado=0.17.1=py312h06a4308_0
  - tinycss2=1.2.1=py312h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h3d55465_1
  - tornado=6.4.2=py312h5eee18b_0
  - traitlets=5.14.3=py312h06a4308_0
  - typing-extensions=4.12.2=py312h06a4308_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py312h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xz=5.6.3=hbcc6ac9_1
  - xz-gpl-tools=5.6.3=hbcc6ac9_1
  - xz-tools=5.6.3=hb9d3cd8_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
